name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
    - uses: actions/checkout@v2
    - uses: rwjblue/setup-volta@v1
    - name: Install
      run: yarn install
    - name: ESLint
      run: |
        yarn lint
        yarn test
  build-and-deploy:
    name: Deploy
    needs: [lint]
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Volta setup
      uses: rwjblue/setup-volta@v1
    - name: Install
      run: yarn install
    - name: Build
      run: yarn build
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist
